/**
 * Data loading utilities for pre-compiled JSON files.
 *
 * All data is loaded at build time — no runtime database queries.
 * JSON files are generated by scripts/compile_site_data.py
 */

import { readFileSync, readdirSync, existsSync } from 'fs';
import { join } from 'path';

const DATA_DIR = join(process.cwd(), 'src', 'data');

function loadJSON<T>(path: string): T {
  const fullPath = join(DATA_DIR, path);
  if (!existsSync(fullPath)) {
    throw new Error(`Data file not found: ${fullPath}. Run scripts/compile_site_data.py first.`);
  }
  return JSON.parse(readFileSync(fullPath, 'utf-8')) as T;
}

// ── Type definitions ────────────────────────────────────────────────

export interface Overview {
  concepts: number;
  clusters: number;
  domains: number;
  objectives: number;
  subjects: number;
  key_stages_count: number;
  thinking_lenses: number;
  difficulty_levels: number;
  prerequisites: number;
  key_stages: Array<{
    id: string;
    name: string;
    year_ids: string[];
    concept_count: number;
  }>;
}

export interface Subject {
  subject_id: string;
  name: string;
  slug: string;
  key_stages: string[];
  total_concepts: number;
  total_domains: number;
  total_clusters: number;
  years: Array<{
    year_id: string;
    year_number: number;
    key_stage: string;
    domains: Array<{
      domain_id: string;
      name: string;
      concept_count: number;
      cluster_count: number;
    }>;
  }>;
}

export interface DifficultyLevel {
  difficulty_id: string;
  label: string;
  level_number: number;
  description: string;
  example_task?: string;
  example_response?: string;
  common_errors?: string;
}

export interface RepresentationStage {
  stage_id: string;
  stage: string;
  stage_number: number;
  description: string;
  resources?: string[];
  example_activity?: string;
  transition_cue?: string;
}

export interface VocabularyTerm {
  term_id: string;
  term: string;
  definition?: string;
  tier?: number;
  word_class?: string;
  introduced?: boolean;
  importance?: string;
}

export interface Concept {
  concept_id: string;
  name: string;
  description?: string;
  concept_type?: string;
  teaching_weight?: number;
  is_keystone?: boolean;
  teaching_guidance?: string;
  key_vocabulary?: string;
  common_misconceptions?: string;
  difficulty_levels?: DifficultyLevel[];
  representation_stages?: RepresentationStage[];
  vocabulary_terms?: VocabularyTerm[];
  delivery_mode?: {
    mode_id: string;
    name: string;
    confidence?: string;
    rationale?: string;
  };
  barriers?: Array<{
    access_req_id: string;
    name: string;
    level: string;
    rationale?: string;
  }>;
}

export interface StudySuggestion {
  name: string;
  type: string;
  description?: string;
  pedagogical_rationale?: string;
  concept_ids: string[];
  template_name?: string;
  cross_curricular: Array<{ target_name: string; hook: string; strength?: string }>;
  period?: string;
  key_figures?: string[];
  disciplinary_concepts?: string[];
  sources?: string[];
  enquiry_question?: string;
  enquiry_type?: string;
  misconceptions?: string[];
  variables?: string;
  writing_outcome?: string;
  genre?: string;
  place?: string;
  contrast?: string;
}

export interface ConceptBarrier {
  concept_id: string;
  concept_name: string;
  barriers: Array<{
    access_req_id: string;
    name: string;
    level: string;
    rationale?: string;
  }>;
}

export interface DomainSendSummary {
  concepts_with_barriers: number;
  total_concepts: number;
  barrier_counts: Record<string, number>;
  top_strategies: Array<{ name: string; description?: string; tier: string; construct_risk?: string; mitigates_count: number }>;
}

export interface Cluster {
  cluster_id: string;
  name: string;
  cluster_type: string;
  rationale?: string;
  is_curated?: boolean;
  teaching_weeks?: number;
  lesson_count?: number;
  thinking_lens_primary?: string;
  concept_ids: string[];
  thinking_lenses: Array<{
    name: string;
    rank: number;
    rationale?: string;
    key_question?: string;
  }>;
  sequenced_after: string[];
}

export interface Domain {
  domain_id: string;
  name: string;
  description?: string;
  curriculum_context?: string;
  subject: string;
  subject_id: string;
  subject_slug: string;
  year_id: string;
  year_number: number;
  key_stage: string;
  key_stage_name: string;
  concepts: Concept[];
  clusters: Cluster[];
  prerequisites: Array<{
    prereq_id: string;
    prereq_name: string;
    from_domain_id?: string;
    from_domain_name?: string;
    target_id: string;
    target_name: string;
  }>;
  suggestions?: StudySuggestion[];
  send_summary?: DomainSendSummary | null;
  concept_barriers?: ConceptBarrier[];
}

export interface DeliveryData {
  modes: Array<{
    id: string;
    name: string;
    description: string;
    color: string;
    order: number;
  }>;
  summary: Array<{
    mode_id: string;
    mode_name: string;
    color: string;
    count: number;
  }>;
  by_subject: Array<{
    subject: string;
    modes: Record<string, { name: string; count: number }>;
  }>;
  by_key_stage: Array<{
    key_stage: string;
    modes: Record<string, { name: string; count: number }>;
  }>;
  requirements: Array<{
    id: string;
    name: string;
    category: string;
    description: string;
    concept_count: number;
    implies_mode: string;
  }>;
}

export interface ThinkingLens {
  id: string;
  name: string;
  description: string;
  key_question: string;
  agent_prompt: string;
  color: string;
  cluster_count: number;
  primary_count: number;
  ks_prompts: Array<{
    key_stage: string;
    agent_prompt: string;
    question_stems: string[];
  }>;
}

export interface LearnerProfile {
  year_id: string;
  year_number: number;
  year_name: string;
  age_range: string;
  content: Record<string, any>;
  pedagogy: Record<string, any>;
  feedback: Record<string, any>;
  interactions: Array<{
    name: string;
    category: string;
    description: string;
    input_method?: string;
    visual_complexity?: string;
  }>;
}

export interface SearchEntry {
  id: string;
  name: string;
  description: string;
  type: string;
  concept_type?: string;
  is_keystone?: boolean;
  subject?: string;
  year_id?: string;
  key_stage?: string;
  domain_id?: string;
  domain_name?: string;
  delivery_mode?: string;
  folder?: string;
  slug?: string;
}

export interface PlannerEntry {
  study_id: string;
  title: string;
  subject: string;
  key_stage: string;
  year_groups: string[];
  duration: string;
  study_type: string;
  status: string;
  coverage: string;
  folder: string;
  slug: string;
}

export interface YearInfo {
  year_id: string;
  year_number: number;
  name: string;
  age_range: string;
  key_stage: string;
  key_stage_name: string;
  subject_count: number;
}

// ── Data loaders ────────────────────────────────────────────────────

export function getOverview(): Overview {
  return loadJSON<Overview>('overview.json');
}

export function getSubjects(): Subject[] {
  return loadJSON<Subject[]>('subjects.json');
}

export function getSubject(slug: string): Subject | undefined {
  const subjects = getSubjects();
  return subjects.find(s => s.slug === slug);
}

export function getDomain(domainId: string): Domain | null {
  try {
    return loadJSON<Domain>(`domains/${domainId}.json`);
  } catch {
    return null;
  }
}

export function getAllDomainIds(): string[] {
  const domainsDir = join(DATA_DIR, 'domains');
  if (!existsSync(domainsDir)) return [];
  return readdirSync(domainsDir)
    .filter(f => f.endsWith('.json'))
    .map(f => f.replace('.json', ''))
    .sort();
}

export function getDeliveryData(): DeliveryData {
  return loadJSON<DeliveryData>('delivery.json');
}

export function getThinkingLenses(): ThinkingLens[] {
  return loadJSON<ThinkingLens[]>('lenses.json');
}

export function getLearnerProfiles(): LearnerProfile[] {
  return loadJSON<LearnerProfile[]>('profiles.json');
}

export function getSearchIndex(): SearchEntry[] {
  return loadJSON<SearchEntry[]>('search_index.json');
}

// ── Planner loaders ─────────────────────────────────────────────────

export function getPlannersManifest(): PlannerEntry[] {
  try {
    return loadJSON<PlannerEntry[]>('planners_manifest.json');
  } catch {
    return [];
  }
}

export function getPlannersBySubjectAndKS(subject: string, ks: string): PlannerEntry[] {
  return getPlannersManifest().filter(
    p => p.subject === subject && p.key_stage === ks
  );
}

export function getPlannersForSubject(subjectName: string): PlannerEntry[] {
  return getPlannersManifest().filter(p => p.subject === subjectName);
}

// ── Year loaders ────────────────────────────────────────────────────

const KS_NAMES: Record<string, string> = {
  EYFS: 'Early Years Foundation Stage',
  KS1: 'Key Stage 1',
  KS2: 'Key Stage 2',
  KS3: 'Key Stage 3',
  KS4: 'Key Stage 4',
};

const YEAR_AGES: Record<string, string> = {
  EYFS: '4-5',
  Y1: '5-6', Y2: '6-7',
  Y3: '7-8', Y4: '8-9', Y5: '9-10', Y6: '10-11',
  Y7: '11-12', Y8: '12-13', Y9: '13-14',
  Y10: '14-15', Y11: '15-16',
};

function yearIdToKS(yearId: string): string {
  if (yearId === 'EYFS') return 'EYFS';
  const n = parseInt(yearId.replace('Y', ''));
  if (n <= 2) return 'KS1';
  if (n <= 6) return 'KS2';
  if (n <= 9) return 'KS3';
  return 'KS4';
}

export function getYears(): YearInfo[] {
  const subjects = getSubjects();
  const overview = getOverview();

  // Collect all year IDs from subjects
  const yearIds = new Set<string>();
  for (const s of subjects) {
    for (const y of s.years) {
      yearIds.add(y.year_id);
    }
  }

  // Build year info
  const years: YearInfo[] = [];
  for (const yid of yearIds) {
    const ks = yearIdToKS(yid);
    const subjectCount = subjects.filter(s => s.years.some(y => y.year_id === yid)).length;
    const yearNum = yid === 'EYFS' ? 0 : parseInt(yid.replace('Y', ''));
    const name = yid === 'EYFS' ? 'Reception' : `Year ${yid.replace('Y', '')}`;

    years.push({
      year_id: yid,
      year_number: yearNum,
      name,
      age_range: YEAR_AGES[yid] || '',
      key_stage: ks,
      key_stage_name: KS_NAMES[ks] || ks,
      subject_count: subjectCount,
    });
  }

  return years.sort((a, b) => a.year_number - b.year_number);
}

export function getYear(id: string): YearInfo | undefined {
  return getYears().find(y => y.year_id === id);
}

export function getSubjectsForYear(yearId: string): Array<Subject & { year_domains: Subject['years'][0]['domains'] }> {
  const subjects = getSubjects();
  const result: Array<Subject & { year_domains: Subject['years'][0]['domains'] }> = [];

  for (const s of subjects) {
    const yearData = s.years.find(y => y.year_id === yearId);
    if (yearData) {
      result.push({ ...s, year_domains: yearData.domains });
    }
  }

  return result.sort((a, b) => {
    // Sort core subjects first
    const priority: Record<string, number> = {
      'English': 1, 'Mathematics': 2, 'Science': 3,
    };
    return (priority[a.name] || 99) - (priority[b.name] || 99) || a.name.localeCompare(b.name);
  });
}
