/**
 * Data loading utilities for pre-compiled JSON files.
 *
 * All data is loaded at build time — no runtime database queries.
 * JSON files are generated by scripts/compile_site_data.py
 */

import { readFileSync, readdirSync, existsSync } from 'fs';
import { join } from 'path';

const DATA_DIR = join(process.cwd(), 'src', 'data');

function loadJSON<T>(path: string): T {
  const fullPath = join(DATA_DIR, path);
  if (!existsSync(fullPath)) {
    throw new Error(`Data file not found: ${fullPath}. Run scripts/compile_site_data.py first.`);
  }
  return JSON.parse(readFileSync(fullPath, 'utf-8')) as T;
}

// ── Type definitions ────────────────────────────────────────────────

export interface Overview {
  concepts: number;
  clusters: number;
  domains: number;
  objectives: number;
  subjects: number;
  key_stages_count: number;
  thinking_lenses: number;
  difficulty_levels: number;
  prerequisites: number;
  key_stages: Array<{
    id: string;
    name: string;
    year_ids: string[];
    concept_count: number;
  }>;
}

export interface Subject {
  subject_id: string;
  name: string;
  slug: string;
  key_stages: string[];
  total_concepts: number;
  total_domains: number;
  total_clusters: number;
  years: Array<{
    year_id: string;
    year_number: number;
    key_stage: string;
    domains: Array<{
      domain_id: string;
      name: string;
      concept_count: number;
      cluster_count: number;
    }>;
  }>;
}

export interface DifficultyLevel {
  difficulty_id: string;
  label: string;
  level_number: number;
  description: string;
  example_task?: string;
  example_response?: string;
  common_errors?: string;
}

export interface RepresentationStage {
  stage_id: string;
  stage: string;
  stage_number: number;
  description: string;
  resources?: string[];
  example_activity?: string;
  transition_cue?: string;
}

export interface Concept {
  concept_id: string;
  name: string;
  description?: string;
  concept_type?: string;
  teaching_weight?: number;
  is_keystone?: boolean;
  teaching_guidance?: string;
  key_vocabulary?: string;
  common_misconceptions?: string;
  difficulty_levels?: DifficultyLevel[];
  representation_stages?: RepresentationStage[];
  delivery_mode?: {
    mode_id: string;
    name: string;
    confidence?: string;
    rationale?: string;
  };
}

export interface Cluster {
  cluster_id: string;
  name: string;
  cluster_type: string;
  rationale?: string;
  is_curated?: boolean;
  teaching_weeks?: number;
  lesson_count?: number;
  thinking_lens_primary?: string;
  concept_ids: string[];
  thinking_lenses: Array<{
    name: string;
    rank: number;
    rationale?: string;
    key_question?: string;
  }>;
  sequenced_after: string[];
}

export interface Domain {
  domain_id: string;
  name: string;
  description?: string;
  curriculum_context?: string;
  subject: string;
  subject_id: string;
  subject_slug: string;
  year_id: string;
  year_number: number;
  key_stage: string;
  key_stage_name: string;
  concepts: Concept[];
  clusters: Cluster[];
  prerequisites: Array<{
    prereq_id: string;
    prereq_name: string;
    from_domain_id?: string;
    from_domain_name?: string;
    target_id: string;
    target_name: string;
  }>;
}

export interface DeliveryData {
  modes: Array<{
    id: string;
    name: string;
    description: string;
    color: string;
    order: number;
  }>;
  summary: Array<{
    mode_id: string;
    mode_name: string;
    color: string;
    count: number;
  }>;
  by_subject: Array<{
    subject: string;
    modes: Record<string, { name: string; count: number }>;
  }>;
  by_key_stage: Array<{
    key_stage: string;
    modes: Record<string, { name: string; count: number }>;
  }>;
  requirements: Array<{
    id: string;
    name: string;
    category: string;
    description: string;
    concept_count: number;
    implies_mode: string;
  }>;
}

export interface ThinkingLens {
  id: string;
  name: string;
  description: string;
  key_question: string;
  agent_prompt: string;
  color: string;
  cluster_count: number;
  primary_count: number;
  ks_prompts: Array<{
    key_stage: string;
    agent_prompt: string;
    question_stems: string[];
  }>;
}

export interface LearnerProfile {
  year_id: string;
  year_number: number;
  year_name: string;
  age_range: string;
  content: Record<string, any>;
  pedagogy: Record<string, any>;
  feedback: Record<string, any>;
  interactions: Array<{
    name: string;
    category: string;
    description: string;
    input_method?: string;
    visual_complexity?: string;
  }>;
}

export interface SearchEntry {
  id: string;
  name: string;
  description: string;
  type: string;
  concept_type?: string;
  is_keystone?: boolean;
  subject?: string;
  year_id?: string;
  key_stage?: string;
  domain_id?: string;
  domain_name?: string;
  delivery_mode?: string;
}

// ── Data loaders ────────────────────────────────────────────────────

export function getOverview(): Overview {
  return loadJSON<Overview>('overview.json');
}

export function getSubjects(): Subject[] {
  return loadJSON<Subject[]>('subjects.json');
}

export function getSubject(slug: string): Subject | undefined {
  const subjects = getSubjects();
  return subjects.find(s => s.slug === slug);
}

export function getDomain(domainId: string): Domain | null {
  try {
    return loadJSON<Domain>(`domains/${domainId}.json`);
  } catch {
    return null;
  }
}

export function getAllDomainIds(): string[] {
  const domainsDir = join(DATA_DIR, 'domains');
  if (!existsSync(domainsDir)) return [];
  return readdirSync(domainsDir)
    .filter(f => f.endsWith('.json'))
    .map(f => f.replace('.json', ''))
    .sort();
}

export function getDeliveryData(): DeliveryData {
  return loadJSON<DeliveryData>('delivery.json');
}

export function getThinkingLenses(): ThinkingLens[] {
  return loadJSON<ThinkingLens[]>('lenses.json');
}

export function getLearnerProfiles(): LearnerProfile[] {
  return loadJSON<LearnerProfile[]>('profiles.json');
}

export function getSearchIndex(): SearchEntry[] {
  return loadJSON<SearchEntry[]>('search_index.json');
}
